"use client";

import React, { useState } from 'react';
import EliteChart from '@/components/viz/EliteChart';

// Mock data for interactive charts
const performanceData = [
    { name: 'Model A', accuracy: 85, f1: 82, value: 0 },
    { name: 'Model B', accuracy: 88, f1: 86, value: 0 },
    { name: 'Model C', accuracy: 92, f1: 90, value: 0 },
];

export default function ReportsPage() {
    const [activeTab, setActiveTab] = useState<'interactive' | 'advanced'>('interactive');

    return (
        <div className="min-h-screen p-8 text-white">
            <header className="mb-8 flex justify-between items-center">
                <div>
                    <h1 className="text-4xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-pink-500 to-violet-500">
                        Elite Reporting
                    </h1>
                    <p className="text-gray-400 mt-2">Comprehensive model performance and data insights.</p>
                </div>
                <div className="flex gap-4">
                    <button
                        onClick={() => setActiveTab('interactive')}
                        className={`px-6 py-2 rounded-full transition-all ${activeTab === 'interactive' ? 'bg-primary text-white shadow-lg shadow-primary/50' : 'bg-gray-800 text-gray-400'}`}
                    >
                        Interactive
                    </button>
                    <button
                        onClick={() => setActiveTab('advanced')}
                        className={`px-6 py-2 rounded-full transition-all ${activeTab === 'advanced' ? 'bg-primary text-white shadow-lg shadow-primary/50' : 'bg-gray-800 text-gray-400'}`}
                    >
                        Scientific (Seaborn)
                    </button>
                </div>
            </header>

            {activeTab === 'interactive' ? (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                    <EliteChart
                        data={performanceData}
                        title="Model Accuracy Comparison"
                        type="bar"
                        dataKey="accuracy"
                    />
                    <EliteChart
                        data={performanceData}
                        title="F1 Score Trends"
                        type="line"
                        dataKey="f1"
                    />
                    <EliteChart
                        data={[
                            { name: 'Class A', value: 400 },
                            { name: 'Class B', value: 300 },
                            { name: 'Class C', value: 300 },
                        ]}
                        title="Target Class Distribution"
                        type="pie"
                        dataKey="value"
                    />
                </div>
            ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                    {/* In a real scenario, these sources would come from the API call to /visualize */}
                    <div className="glass-panel p-6 flex flex-col items-center justify-center min-h-[400px]">
                        <p className="text-gray-500 italic mb-4">Correlation Matrix (Generated by Seaborn)</p>
                        <div className="w-full h-64 bg-gray-800/50 rounded flex items-center justify-center border border-dashed border-gray-600">
                            <span className="text-xs text-gray-400">Plot Image from Backend</span>
                        </div>
                    </div>
                    <div className="glass-panel p-6 flex flex-col items-center justify-center min-h-[400px]">
                        <p className="text-gray-500 italic mb-4">Feature Distribution (Violin Plot)</p>
                        <div className="w-full h-64 bg-gray-800/50 rounded flex items-center justify-center border border-dashed border-gray-600">
                            <span className="text-xs text-gray-400">Plot Image from Backend</span>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}
